# Generated by Django 3.0.6 on 2020-09-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckywinner', '0002_participants_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
