# Generated by Django 3.0.8 on 2020-10-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckywinner', '0004_auto_20200929_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='facebook_id',
            field=models.CharField(default=12345, max_length=1000),
            preserve_default=False,
        ),
    ]
